services:
  app:
    build: .
    ports:
      - 5000:5000
      - 9229:9229 #for debugging
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    command: ["npm", "start"] #change when it's time
    environment:
      - PORT=5000
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
